accounts:
  - name: alice
    coins: ["2000000000000000ufetf"]
  - name: bob
    coins: ["100000000000000000ufetf"]
  - name: faucet
    coins: ["50000000000000ufetf",]
validator:
  name: alice
  staked: "100000000ufetf"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: faucet
  coins: ["50000000000000ufetf"]
genesis:
  chain_id: "defund"
  app_state:
    staking:
      params:
        bond_denom: "ufetf"
    mint:
      params:
        mint_denom: "ufetf"
    crisis:
      constant_fee:
        denom: "ufetf"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "ufetf"
