src: defund
dest: osmosis
mnemonic: alley afraid soup fall idea toss can goose become valve initial strong forward bright dish figure check leopard decide warfare hub unusual join cart
srcConnection: connection-3
destConnection: connection-2468
